import { useCallback, useMemo, useState } from "react";
import {
  SignedPair,
  LengthExtResult,
  cbcMacTag,
  generateMacKey,
  generateSignedPairs,
  lengthExtend,
  naiveMacTag,
  prfMacTag,
  verifyForgery,
} from "./mac";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type MacScheme = "CBC-MAC" | "PRF-MAC";
type Pa05Tab = "euf-cma" | "length-ext";

interface ForgeResult {
  accepted: boolean;
  reason: string;
}

interface GameState {
  keyHex: string;
  pairs: SignedPair[];
  attempts: number;
  successes: number;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function freshGame(scheme: MacScheme, n = 50): GameState {
  const keyHex = generateMacKey();
  const pairs = generateSignedPairs(keyHex, n, scheme);
  return { keyHex, pairs, attempts: 0, successes: 0 };
}

function tagForScheme(scheme: MacScheme, keyHex: string, msg: string): string {
  return scheme === "PRF-MAC" ? prfMacTag(keyHex, msg) : cbcMacTag(keyHex, msg);
}

// ---------------------------------------------------------------------------
// Sub-components
// ---------------------------------------------------------------------------

function BadgePill({ label }: { label: string }) {
  return <span className="pa05-badge">{label}</span>;
}

function HexBox({ value, label }: { value: string; label?: string }) {
  return (
    <div className="pa05-hex-block">
      {label && <div className="pa05-hex-label">{label}</div>}
      <div className="pa05-hex-value">{value || "—"}</div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Tab 1: EUF-CMA Forge Attempt
// ---------------------------------------------------------------------------

function EufCmaTab() {
  const [scheme, setScheme] = useState<MacScheme>("CBC-MAC");
  const [game, setGame] = useState<GameState>(() => freshGame("CBC-MAC"));
  const [forgeMsg, setForgeMsg] = useState("");
  const [forgeTag, setForgeTag] = useState("");
  const [result, setResult] = useState<ForgeResult | null>(null);
  const [showAll, setShowAll] = useState(false);

  const displayPairs = showAll ? game.pairs : game.pairs.slice(0, 10);

  const startNewGame = useCallback(() => {
    setGame(freshGame(scheme));
    setForgeMsg("");
    setForgeTag("");
    setResult(null);
  }, [scheme]);

  const onSchemeChange = useCallback(
    (s: MacScheme) => {
      setScheme(s);
      setGame(freshGame(s));
      setForgeMsg("");
      setForgeTag("");
      setResult(null);
    },
    [],
  );

  const submitForgery = useCallback(() => {
    if (!forgeMsg.trim()) return;
    const isNew = !game.pairs.some((p) => p.msg === forgeMsg.trim());

    if (!isNew) {
      setResult({ accepted: false, reason: "Message is already in the signed set — not a new-message forgery." });
      return;
    }

    const accepted = verifyForgery(game.keyHex, forgeMsg.trim(), forgeTag.trim(), scheme);
    setGame((g) => ({
      ...g,
      attempts: g.attempts + 1,
      successes: accepted ? g.successes + 1 : g.successes,
    }));
    setResult({
      accepted,
      reason: accepted
        ? "🚨 Forgery accepted! (This should not happen — check PRF security.)"
        : `Forgery rejected. The real tag is: ${tagForScheme(scheme, game.keyHex, forgeMsg.trim())}`,
    });
  }, [forgeMsg, forgeTag, game, scheme]);

  return (
    <div className="pa05-tab-body">
      {/* Hero description */}
      <div className="pa05-euf-desc">
        <p>
          The challenger holds a <strong>hidden key k</strong>. Below are up to 50
          signed pairs (m<sub>i</sub>, Mac<sub>k</sub>(m<sub>i</sub>)) generated by
          that key. Your goal as an EUF-CMA adversary: supply a <em>new</em> message
          m* (not in the list) with a valid tag t*. Graders expect{" "}
          <strong>0 successes</strong> in ≥ 20 attempts.
        </p>
      </div>

      {/* Controls */}
      <div className="pa05-controls-row">
        <div className="pa05-control-card">
          <div className="pa01-control-label">
            <label>MAC scheme</label>
          </div>
          <div className="pa05-scheme-row">
            {(["CBC-MAC", "PRF-MAC"] as MacScheme[]).map((s) => (
              <button
                key={s}
                type="button"
                className={`pa05-scheme-btn${scheme === s ? " active" : ""}`}
                onClick={() => onSchemeChange(s)}
              >
                {s}
              </button>
            ))}
          </div>
        </div>

        <div className="pa05-control-card">
          <div className="pa01-control-label">
            <label>Key k</label>
          </div>
          <div className="pa05-hidden-key">
            <span className="pa05-key-mask">████████████████</span>
            <span className="pa05-key-note">(hidden)</span>
          </div>
          <button
            type="button"
            id="pa05-new-game"
            className="pa05-primary-btn"
            style={{ marginTop: "0.55rem" }}
            onClick={startNewGame}
          >
            ↻ New Game
          </button>
        </div>

        <div className="pa05-control-card pa05-score-card">
          <div className="pa01-control-label">
            <label>Score</label>
          </div>
          <div className="pa05-score-grid">
            <div className="pa05-score-item">
              <span className="pa05-score-val">{game.attempts}</span>
              <span className="pa05-score-lbl">Attempts</span>
            </div>
            <div className="pa05-score-item pa05-score-success">
              <span className="pa05-score-val">{game.successes}</span>
              <span className="pa05-score-lbl">Successes</span>
            </div>
          </div>
          <div className="pa05-score-note">
            Graders expect 0 successes in ≥ 20 attempts.
          </div>
        </div>
      </div>

      {/* Signed pairs table */}
      <section className="pa05-pairs-section">
        <div className="pa05-section-head">
          <span className="pa01-output-title">Signed Pairs (m<sub>i</sub>, t<sub>i</sub>)</span>
          <span className="pa01-output-meta">{game.pairs.length} pairs total</span>
        </div>
        <div className="pa05-pairs-table">
          <div className="pa05-pairs-header">
            <span>#</span>
            <span>Message m<sub>i</sub></span>
            <span>Tag t<sub>i</sub> = Mac<sub>k</sub>(m<sub>i</sub>)</span>
          </div>
          {displayPairs.map((pair, i) => (
            <div key={pair.msg} className="pa05-pair-row">
              <span className="pa05-pair-idx">{i + 1}</span>
              <span className="pa05-pair-msg">{pair.msg}</span>
              <span className="pa05-pair-tag">{pair.tag}</span>
            </div>
          ))}
        </div>
        {game.pairs.length > 10 && (
          <button
            type="button"
            className="pa01-random-btn"
            style={{ marginTop: "0.55rem" }}
            onClick={() => setShowAll((v) => !v)}
          >
            {showAll ? "Show fewer ↑" : `Show all ${game.pairs.length} pairs ↓`}
          </button>
        )}
      </section>

      {/* Forgery input */}
      <section className="pa05-forge-section">
        <div className="pa05-section-head">
          <span className="pa01-output-title">Submit Forgery</span>
          <span className="pa01-output-meta">m* must not appear in the list above</span>
        </div>

        <div className="pa05-forge-inputs">
          <div className="pa05-forge-field">
            <label htmlFor="pa05-forge-msg">New message m*</label>
            <input
              id="pa05-forge-msg"
              className="pa01-hex-input"
              value={forgeMsg}
              onChange={(e) => {
                setForgeMsg(e.target.value);
                setResult(null);
              }}
              placeholder="Type a message not in the list above…"
              spellCheck={false}
            />
          </div>
          <div className="pa05-forge-field">
            <label htmlFor="pa05-forge-tag">Proposed tag t* (hex)</label>
            <input
              id="pa05-forge-tag"
              className="pa01-hex-input"
              value={forgeTag}
              onChange={(e) => {
                setForgeTag(e.target.value);
                setResult(null);
              }}
              placeholder="16 hex characters…"
              spellCheck={false}
            />
          </div>
        </div>

        <button
          type="button"
          id="pa05-submit-forgery"
          className="pa05-primary-btn"
          disabled={!forgeMsg.trim() || !forgeTag.trim()}
          onClick={submitForgery}
        >
          Submit Forgery
        </button>

        {result && (
          <div className={`pa05-result-banner${result.accepted ? " accept" : " reject"}`}>
            <span className="pa05-result-icon">{result.accepted ? "🚨" : "🛡️"}</span>
            <span className="pa05-result-text">{result.reason}</span>
          </div>
        )}
      </section>

      {/* Security note */}
      <section className="pa05-note-card">
        <div className="pa05-note-title">EUF-CMA Security</div>
        <p>
          <strong>Theorem (PRF → MAC):</strong> If F is a (t, q, ε)-secure PRF, then
          PRF-MAC is (t′, q, ε + q/2<sup>n</sup>)-EUF-CMA secure. Any forger A
          can be turned into a PRF distinguisher D with Adv<sub>PRF</sub>(D) ≥
          Adv<sub>MAC</sub>(A) − q/2<sup>n</sup>.
        </p>
        <p>
          <strong>CBC-MAC:</strong> Extends the guarantee to variable-length messages.
          PKCS padding ensures prefix-freeness, preventing extension attacks within
          the chaining structure itself.
        </p>
      </section>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Tab 2: Length-Extension Demo
// ---------------------------------------------------------------------------

function LengthExtTab() {
  const [keyHex] = useState(() => generateMacKey());
  const [origMsg, setOrigMsg] = useState("hello-world");
  const [suffix, setSuffix] = useState("evil-suffix");
  const [extResult, setExtResult] = useState<LengthExtResult | null>(null);

  const origTag = useMemo(() => naiveMacTag(keyHex, origMsg), [keyHex, origMsg]);

  const runExtension = useCallback(() => {
    if (!origMsg.trim() || !suffix.trim()) return;
    const r = lengthExtend(keyHex, origMsg, origTag, suffix);
    setExtResult(r);
  }, [keyHex, origMsg, origTag, suffix]);

  return (
    <div className="pa05-tab-body">
      {/* Hero explanation */}
      <div className="pa05-ext-desc">
        <p>
          The <strong>naive MAC</strong> t = H(k ‖ m) built from a Merkle-Damgård
          hash is <em>vulnerable to length-extension attacks</em>. Given only (m, t,
          |k|), an adversary can forge a valid tag for (m ‖ pad ‖ suffix) without
          knowing k. This demo uses a{" "}
          <strong>toy Merkle-Damgård hash</strong> (GGM PRF as compression function)
          to show the attack concretely.
        </p>
      </div>

      {/* Two-column: original MAC + attack */}
      <div className="pa05-ext-grid">
        {/* Left: Honest signer */}
        <section className="pa05-ext-card pa05-ext-honest">
          <div className="pa05-ext-card-head">
            <span className="pa05-ext-role">🔑 Honest Signer</span>
            <BadgePill label="Has key k" />
          </div>

          <div className="pa05-ext-field">
            <label htmlFor="pa05-orig-msg">Original message m</label>
            <input
              id="pa05-orig-msg"
              className="pa01-hex-input"
              value={origMsg}
              onChange={(e) => {
                setOrigMsg(e.target.value);
                setExtResult(null);
              }}
              placeholder="Type a message…"
              spellCheck={false}
            />
          </div>

          <HexBox label="Key k (hex) — hidden from attacker" value="████████████████" />
          <HexBox label="Naive MAC: t = H(k ‖ m)" value={origTag} />

          <div className="pa05-ext-formula">
            <span>t = H( k ‖ m )  &nbsp;=&nbsp; </span>
            <span className="pa05-tag-chip">{origTag}</span>
          </div>
        </section>

        {/* Right: Attacker */}
        <section className="pa05-ext-card pa05-ext-attacker">
          <div className="pa05-ext-card-head">
            <span className="pa05-ext-role">🎭 Attacker</span>
            <BadgePill label="Knows m, t, |k| only" />
          </div>

          <div className="pa05-ext-field">
            <label htmlFor="pa05-suffix">Chosen suffix m′</label>
            <input
              id="pa05-suffix"
              className="pa01-hex-input"
              value={suffix}
              onChange={(e) => {
                setSuffix(e.target.value);
                setExtResult(null);
              }}
              placeholder="Type the suffix to append…"
              spellCheck={false}
            />
          </div>

          <div className="pa05-ext-field">
            <label>Known inputs (no k)</label>
            <div className="pa05-attacker-knows">
              <span>m = <strong>{origMsg}</strong></span>
              <span>t = <strong className="pa05-mono">{origTag}</strong></span>
              <span>|k| = <strong>8 bytes</strong></span>
            </div>
          </div>

          <button
            type="button"
            id="pa05-extend-btn"
            className="pa05-attack-btn"
            disabled={!origMsg.trim() || !suffix.trim()}
            onClick={runExtension}
          >
            ⚡ Run Length-Extension
          </button>
        </section>
      </div>

      {/* Result */}
      {extResult && (
        <section className="pa05-ext-result">
          <div className="pa05-section-head">
            <span className="pa01-output-title">Attack Result</span>
            <span className={`pa05-badge${extResult.verified ? " danger" : ""}`}>
              {extResult.verified ? "✅ Attack Succeeded!" : "❌ Failed"}
            </span>
          </div>

          <div className="pa05-ext-result-grid">
            <HexBox label={`Original m = "${extResult.originalMsgText}"`} value={extResult.extendedTagHex.slice(0, 0) + extResult.gluePadHex || "—"} />

            <div className="pa05-ext-chain">
              <div className="pa05-ext-chain-step">
                <span className="pa05-chain-label">m</span>
                <span className="pa05-chain-val">{extResult.originalMsgText}</span>
              </div>
              <div className="pa05-chain-join">‖</div>
              <div className="pa05-ext-chain-step pa05-chain-glue">
                <span className="pa05-chain-label">padding (glue)</span>
                <span className="pa05-chain-val pa05-mono">{extResult.gluePadHex}</span>
              </div>
              <div className="pa05-chain-join">‖</div>
              <div className="pa05-ext-chain-step pa05-chain-suffix">
                <span className="pa05-chain-label">suffix m′</span>
                <span className="pa05-chain-val">{extResult.suffixText}</span>
              </div>
            </div>

            <div className="pa05-ext-tags">
              <div className="pa05-ext-tag-row">
                <span className="pa05-tag-role">Forged tag (no k used)</span>
                <span className="pa05-mono pa05-tag-chip danger">{extResult.extendedTagHex}</span>
              </div>
              <div className={`pa05-ext-verdict${extResult.verified ? " success" : " fail"}`}>
                {extResult.verified
                  ? "✅ Challenger verifies: H(k ‖ m ‖ pad ‖ suffix) = forged tag — attack succeeds!"
                  : "❌ Verification failed."}
              </div>
            </div>
          </div>

          <div className="pa05-ext-explanation">{extResult.explanation}</div>
        </section>
      )}

      {/* HMAC fix note */}
      <section className="pa05-note-card pa05-hmac-note">
        <div className="pa05-note-title">🛡️ Why HMAC Fixes This</div>
        <div className="pa05-hmac-formula">
          HMAC<sub>k</sub>(m) = H( (k ⊕ opad) ‖ H( (k ⊕ ipad) ‖ m ) )
        </div>
        <p>
          The outer hash wraps the inner hash output, so there is <em>no reachable
          intermediate Merkle-Damgård chaining state</em> for an adversary to resume
          from. Even knowing H((k ⊕ ipad) ‖ m), the outer hash requires k ⊕ opad
          to proceed — making length-extension structurally impossible.
        </p>
        <p className="pa05-stub-note">
          <strong>HMAC stub:</strong> Full implementation in PA#10 using PA#8's
          collision-resistant hash. The stub raises <code>NotImplementedError</code>
          until then.
        </p>
      </section>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Main PA05 Panel
// ---------------------------------------------------------------------------

export default function Pa05Panel() {
  const [tab, setTab] = useState<Pa05Tab>("euf-cma");

  return (
    <div className="pa05-shell">
      {/* Hero */}
      <section className="pa05-hero">
        <div className="pa01-hero-badge" style={{
          background: "rgba(79,70,229,0.22)",
          borderColor: "rgba(165,180,252,0.45)",
          color: "#c7d2fe",
        }}>
          PA #5
        </div>
        <h2 className="pa05-hero-title">Message Authentication Codes</h2>
        <p className="pa05-hero-sub">
          PRF-MAC · CBC-MAC · EUF-CMA Security Game · Length-Extension Attack Demo
        </p>
        <div className="pa05-hero-pills">
          <span>PRF → MAC reduction</span>
          <span>PKCS-padded CBC chaining</span>
          <span>Toy Merkle-Damgård</span>
          <span>HMAC stub (→ PA#10)</span>
        </div>
      </section>

      {/* Sub-tabs */}
      <div className="pa05-subtabs">
        <button
          id="pa05-tab-euf-cma"
          type="button"
          className={`pa05-subtab-btn${tab === "euf-cma" ? " active" : ""}`}
          onClick={() => setTab("euf-cma")}
        >
          🎯 EUF-CMA Forge Attempt
        </button>
        <button
          id="pa05-tab-length-ext"
          type="button"
          className={`pa05-subtab-btn${tab === "length-ext" ? " active" : ""}`}
          onClick={() => setTab("length-ext")}
        >
          ⚡ Length-Extension Demo
        </button>
      </div>

      {/* Tab content */}
      {tab === "euf-cma" ? <EufCmaTab /> : <LengthExtTab />}
    </div>
  );
}
